// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWQqY2qlECGpofO6IYtSzQibxm8zu0PI',
    appId: '1:1041646649035:web:f5a64b916d360aca39254e',
    messagingSenderId: '1041646649035',
    projectId: 'todo-list-provider-bbd3a',
    authDomain: 'todo-list-provider-bbd3a.firebaseapp.com',
    storageBucket: 'todo-list-provider-bbd3a.appspot.com',
    measurementId: 'G-J7WV9RKG07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvt7SKxCBrEFwXz5ZsfjsT6T_wFDaD4fg',
    appId: '1:1041646649035:android:6e2c9f518fd3c99d39254e',
    messagingSenderId: '1041646649035',
    projectId: 'todo-list-provider-bbd3a',
    storageBucket: 'todo-list-provider-bbd3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Qrxfutidzc9FsKtEBC1fUV2i0p1-1-U',
    appId: '1:1041646649035:ios:28b245eb8a987d9139254e',
    messagingSenderId: '1041646649035',
    projectId: 'todo-list-provider-bbd3a',
    storageBucket: 'todo-list-provider-bbd3a.appspot.com',
    androidClientId: '1041646649035-j6rmlsl1glf3i7iatqpig5dkd1ufng4k.apps.googleusercontent.com',
    iosClientId: '1041646649035-ka0shuvi3ufdvomg5999mq6a4mbmm2g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Qrxfutidzc9FsKtEBC1fUV2i0p1-1-U',
    appId: '1:1041646649035:ios:28b245eb8a987d9139254e',
    messagingSenderId: '1041646649035',
    projectId: 'todo-list-provider-bbd3a',
    storageBucket: 'todo-list-provider-bbd3a.appspot.com',
    androidClientId: '1041646649035-j6rmlsl1glf3i7iatqpig5dkd1ufng4k.apps.googleusercontent.com',
    iosClientId: '1041646649035-ka0shuvi3ufdvomg5999mq6a4mbmm2g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );
}
